spring.application.name=LABORATORIO_PANADERIA

# 1. URL de conexión (Reemplaza 'localhost:3306' si está en otro servidor y 'nombre_tu_base_datos')
spring.datasource.url=jdbc:mysql://localhost:3306/panaderia_proyect
# 2. Credenciales de acceso a tu MySQL
spring.datasource.username=root
spring.datasource.password=root

# 3. Driver de la base de datos (Opcional en versiones nuevas de Spring, pero recomendado)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Estrategia de creación de tablas (Hibernate)
# 'update' creará las tablas automáticamente si no existen o añadirá columnas nuevas si detecta cambios
spring.jpa.hibernate.ddl-auto=update

# 5. Mostrar las consultas SQL en la consola (Muy útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true